spring.application.name=PMSS

spring.thymeleaf.cache=false
logging.level.org.springframework.security=DEBUG

#This path may need to change, im not sure what the best way is for everyone to access the database
#This was what it was before: spring.datasource.url=jdbc:sqlite:database/PMSS.db
spring.datasource.url=jdbc:sqlite:C:/Users/User/IdeaProjects/PMSS-2/PMSS/database/PMSS.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always