spring.application.name=PMSS
spring.thymeleaf.cache=false

# SQLite Database
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:database/PMSS.db
spring.sql.init.mode=always

# Security Logging - removing .log to convert to .xml
#logging.file.name=logs/pmss-security.log

# Multipart upload limits
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB